name: wordle_solver
description: "A mobile Wordle solver."

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  confetti: ^0.7.0
  fluttertoast: ^8.2.5
  virtual_keyboard_multi_language: ^1.0.3
  flutter_shakemywidget: ^1.0.5+1
  fade_and_translate: ^0.1.3
  rust_lib_wordle_solver:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
