[package]
name = "rust_lib_wordle_solver"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.35"
phf = { version = "0.11.2", features = ["macros"] }

[build-dependencies]
phf_codegen = "0.11.2"
